include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0.0
PKG_RELEASE:=3
PKG_MAINTAINER:=nymanyim
PKG_LICENSE:=MIT

LUCI_TITLE:=LuCI support for openwrt2mqtt
LUCI_DEPENDS:=+luci-base +openwrt2mqtt

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
